### ISSUE TITLE
JSON::ParserError when draft_destroying a widget which was just created

### ISSUE THREAD

**Issue by npafundi** [liveeditor/draftsman#12]
Hey Chris,

It's been a (very) long time, but I'm finally looping back around to putting drafts into our application.  Today I ran across an issue, and I have a 100% reproducible case.

I created a simple app with the Postgres JSON data type (and used the install switch to enable it for drafts).  The app has a single table and model, `Widget`, and I added drafts to this table.

If I create a draft Widget, then later draft_destroy this Widget (without publishing in between), I get a `JSON::ParserError`.

For example, in the console, I can do the following to reproduce:
```
w = Widget.new(some_attr: "hello")
w.draft_creation
```

At this point, I can see the Widget and draft, and all looks good.  Running `w.draft_destroy` will result in:

```
JSON::ParserError: 795: unexpected token at '---
id: 1
item_type: Widget
item_id: 1
event: create
whodunnit:
object:
  id: 1
  some_attr: hi
  created_at: '2015-03-23T22:42:15.628Z'
  updated_at: '2015-03-23T22:42:15.628Z'
  draft_id:
  published_at:
  trashed_at:
previous_draft:
created_at: 2015-03-23 22:42:15.651663000 Z
updated_at: 2015-03-23 22:42:15.651663000 Z
'
```

I'm not sure if we're supposed to handle draft deletion differently for non-published content.  If so, I can just change what I'm doing.

Let me know if you need more info!

Thanks!
Nick
